apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: deployment-supervisor
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: deployment-supervisor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-supervisor
subjects:
- kind: ServiceAccount
  name: deployment-supervisor
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-supervisor

